export type MicroGuide = {
  id: string;
  matches: RegExp;
  title: string;
  source: string;
  sourceUrl: string;
  reviewedAt: string;
  frames: Array<{ caption: string; alt: string; scene: 'offer' | 'notice' | 'try' }>;
};

// Reviewed, source-linked prompts only. These illustrations show a possible play setup,
// not a diagnostic sequence or a timeline for when a child should do it.
export const microGuides: MicroGuide[] = [
  { id: 'hand-transfer', matches: /transfer|passes?.*hand/i, title: 'Passing an object between hands', source: 'CDC Learn the Signs. Act Early.', sourceUrl: 'https://www.cdc.gov/act-early/milestones/index.html', reviewedAt: '2026-09-01', frames: [{ scene: 'offer', caption: 'Offer one safe, easy-to-hold object.', alt: 'An open hand offering a soft block.' }, { scene: 'notice', caption: 'Pause and notice how your child explores it.', alt: 'Two hands holding a soft block.' }, { scene: 'try', caption: 'Place another object nearby, without asking for a performance.', alt: 'Two hands beside two soft blocks.' }] },
  { id: 'pincer-grasp', matches: /thumb and (?:pointer|fore)finger|pincer/i, title: 'Picking up a small object', source: 'CDC Learn the Signs. Act Early.', sourceUrl: 'https://www.cdc.gov/act-early/milestones/index.html', reviewedAt: '2026-09-01', frames: [{ scene: 'offer', caption: 'Use only a safe, age-appropriate object and stay close.', alt: 'An adult hand placing a safe, large pretend food piece on a tray.' }, { scene: 'notice', caption: 'Give your child time to reach and explore.', alt: 'A small hand reaching toward a pretend food piece.' }, { scene: 'try', caption: 'Notice the approach, not a perfect grasp.', alt: 'A small hand holding a pretend food piece.' }] },
  { id: 'joint-attention', matches: /points to show|show you something interesting|joint attention/i, title: 'Sharing something interesting', source: 'CDC Learn the Signs. Act Early.', sourceUrl: 'https://www.cdc.gov/act-early/milestones/index.html', reviewedAt: '2026-09-01', frames: [{ scene: 'offer', caption: 'Notice something interesting together.', alt: 'An adult and child looking toward a bright shape.' }, { scene: 'notice', caption: 'Look where your child looks or gestures.', alt: 'An adult hand and small hand pointing toward the same bright shape.' }, { scene: 'try', caption: 'Respond warmly with simple words about it.', alt: 'Two speech bubbles beside an adult and child.' }] },
  { id: 'pointing-for-help', matches: /points to ask|point.*help/i, title: 'Asking for help with a gesture', source: 'CDC Learn the Signs. Act Early.', sourceUrl: 'https://www.cdc.gov/act-early/milestones/index.html', reviewedAt: '2026-09-01', frames: [{ scene: 'offer', caption: 'Place a familiar item just out of reach.', alt: 'A favorite ball on a low shelf.' }, { scene: 'notice', caption: 'Wait for any look, reach, sound, or gesture.', alt: 'A small hand reaching toward a ball.' }, { scene: 'try', caption: 'Name the request and help without pressure.', alt: 'An adult passing a ball to a small hand.' }] },
  { id: 'pull-to-stand', matches: /pulls? up to stand|pulling to stand/i, title: 'Pulling up with support nearby', source: 'CDC Learn the Signs. Act Early.', sourceUrl: 'https://www.cdc.gov/act-early/milestones/index.html', reviewedAt: '2026-09-01', frames: [{ scene: 'offer', caption: 'Clear the area and choose a sturdy, low support.', alt: 'A clear floor beside a stable couch.' }, { scene: 'notice', caption: 'Stay close while your child explores the support.', alt: 'A small figure holding a stable couch while an adult stays nearby.' }, { scene: 'try', caption: 'Let your child set the pace and stop when they are done.', alt: 'A small figure standing beside a stable couch with an adult nearby.' }] },
  { id: 'directions-with-gesture', matches: /follows directions given with both a gesture/i, title: 'A direction with a gesture', source: 'CDC Learn the Signs. Act Early.', sourceUrl: 'https://www.cdc.gov/act-early/milestones/index.html', reviewedAt: '2026-09-01', frames: [{ scene: 'offer', caption: 'Use one short phrase with a clear gesture.', alt: 'An adult open hand beside a toy.' }, { scene: 'notice', caption: 'Pause long enough for a response.', alt: 'An adult and child pausing beside a toy.' }, { scene: 'try', caption: 'Treat any attempt to join in as a shared turn.', alt: 'A child handing a toy toward an adult hand.' }] },
  { id: 'one-step-directions', matches: /follows one-step directions without/i, title: 'A calm one-step direction', source: 'CDC Learn the Signs. Act Early.', sourceUrl: 'https://www.cdc.gov/act-early/milestones/index.html', reviewedAt: '2026-09-01', frames: [{ scene: 'offer', caption: 'Choose one familiar object and one short phrase.', alt: 'A familiar ball next to one simple speech bubble.' }, { scene: 'notice', caption: 'Wait quietly before repeating yourself.', alt: 'An adult waiting with relaxed hands.' }, { scene: 'try', caption: 'Keep it playful, even if the answer is a look or a laugh.', alt: 'An adult and child sharing a ball.' }] },
  { id: 'parallel-play', matches: /plays next to other children|parallel play/i, title: 'Playing alongside another child', source: 'CDC Learn the Signs. Act Early.', sourceUrl: 'https://www.cdc.gov/act-early/milestones/index.html', reviewedAt: '2026-09-01', frames: [{ scene: 'offer', caption: 'Set out similar safe toys with room for each child.', alt: 'Two sets of blocks on a clear floor.' }, { scene: 'notice', caption: 'Let each child choose their own play.', alt: 'Two small figures building separate block towers.' }, { scene: 'try', caption: 'Notice moments of looking, copying, or simply being nearby.', alt: 'Two small figures playing side by side with blocks.' }] },
];

export function microGuideFor(title: string) {
  return microGuides.find((guide) => guide.matches.test(title)) ?? null;
}
